# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20190505_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default=9407010979, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, help_text='Shipping to?', max_length=120, null=True),
        ),
    ]
