# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-14 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='phone',
            field=models.CharField(default=1111111111, max_length=10),
            preserve_default=False,
        ),
    ]
