# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0007_auto_20190309_2206'),
        ('carts', '0002_auto_20190310_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='books_removed',
            field=models.ManyToManyField(blank=True, related_name='books_removed', to='booksapp.Book'),
        ),
    ]
