# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-24 15:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('displayTitle', models.CharField(blank=True, max_length=200)),
                ('language', models.CharField(choices=[('HINDI', 'Hindi'), ('ENGLISH', 'English'), ('MARATHI', 'Marathi')], default='English', max_length=200)),
                ('format', models.CharField(choices=[('PAPERBACK', 'Paperback'), ('HARDCOVER', 'Hardcover'), ('EBOOK', 'Ebook')], default='Paperback', max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('publishingDate', models.DateField(blank=True)),
                ('isbn10', models.CharField(blank=True, max_length=200, unique=True)),
                ('isbn13', models.CharField(blank=True, max_length=200, unique=True)),
                ('dimension', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('numberOfPages', models.BigIntegerField()),
                ('category', models.CharField(blank=True, max_length=200)),
                ('subCategory', models.CharField(blank=True, max_length=200)),
                ('edition', models.CharField(blank=True, max_length=200)),
                ('numberOfCopiesSold', models.BigIntegerField(default=0)),
                ('pustakalayRating', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('avgcustomerRating', models.BigIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('newArrival', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('context', models.CharField(blank=True, max_length=200)),
                ('rank', models.FloatField(default=0)),
                ('translatedBy', models.CharField(blank=True, max_length=200)),
                ('sku', models.CharField(blank=True, default='pu', max_length=200, unique=True)),
                ('price', models.BigIntegerField(default=200)),
                ('maxretailprice', models.BigIntegerField(default=200)),
                ('minimumprice', models.BigIntegerField(default=200)),
                ('discount', models.BigIntegerField(default=200)),
                ('inventory', models.BigIntegerField(default=200)),
                ('description', models.TextField(max_length=20000)),
                ('author', models.CharField(max_length=200)),
                ('aboutAuthor', models.TextField(blank=True, max_length=20000)),
                ('image_front', models.ImageField(blank=True, upload_to='')),
                ('image_back', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
