# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-24 18:19
from __future__ import unicode_literals

import booksapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_back',
            field=models.ImageField(blank=True, null=True, upload_to=booksapp.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_front',
            field=models.ImageField(blank=True, null=True, upload_to=booksapp.models.upload_image_path),
        ),
    ]
