# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-09 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0006_auto_20190309_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='products',
            new_name='books',
        ),
    ]
