# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190414_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailactivation',
            name='user',
        ),
        migrations.DeleteModel(
            name='GuestEmail',
        ),
        migrations.DeleteModel(
            name='EmailActivation',
        ),
    ]
