# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190501_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address_final',
        ),
    ]
